### ISSUE TITLE
Prospector: f-string invalid syntax for Python 3.6

### ISSUE THREAD

**Issue by mxlei01** [codacy/codacy-meta#186]
I'm getting an invalid syntax on prospector even though I added a codacy.yml file:

```
engines:
 prospector:
   enabled: true
   python_version: 3
```
