### ISSUE TITLE
Pattern "Reports lines with exceeded length" doesn't take line value into account 

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#300]
When using own config file with the following section:
```
MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
...
  MaximumLineLength:
    active: true
    maxLineLength: 120

```
Detekt doesn't seem to be taking the 120 into account, since an issue is thrown when file line is only:
`);`
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9452'>Zendesk ticket #9452</a>)<br>gz#9452</i>
