### ISSUE TITLE
Python 2.7 print statement invalid syntax?

### ISSUE THREAD

**Issue by mathieugouin** [codacy/codacy-meta#342]
I'm using github with codacy.  

Here is my .codacy.yaml:

```
engines:
 pylint:
   enabled: true
   python_version: 2

 prospector:
   enabled: true
   python_version: 2
```

Yet, I have this strange prospector finding at every first print statement of my files.  Here is an example:

```
def simulate():
invalid syntax
    print "simulate()"
```

The detailed issue is as follows:

> Why is this an issue?
> pyflakes
> A simple program which checks Python source files for errors.
> 
> Pyflakes analyzes programs and detects various errors. It works by parsing the source file, not importing it, so it is safe to use on modules with side effects. It’s also much faster.
> 
> Related code pattern
> pyflakes tool
> A simple program which checks Python source files for errors.
> 
> Python Code Style
> Powered by Prospector

Am I missing something here?

Thanks!
